#!/usr/bin/env ansible-playbook
---
- name: Ubuntu
  hosts: localhost
  become: yes
  vars:
    hub_version: 2.11.1
    ubuntu_packages:
      - net-tools
      - zsh
      - git
      - openssh-server
      - vim
      - curl
      - fonts-noto
      - xsel
      - peco
      - silversearcher-ag
    snap_packages:
      - jq
    snap_classic_packages:
      - google-cloud-sdk
  environment: "{{ local_env | default({}) }}"
  pre_tasks:
    - name: Change /etc/environment
      lineinfile:
          path: /etc/environment
          regexp: "^{{ item.key }}=.+"
          line: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ local_env | default({}) }}"
      notify: Restart Snapd
    - meta: flush_handlers

    - name: Ensure Useful Packages
      apt: update_cache=yes cache_valid_time="{{ 3600*24*3 }}" name="{{ubuntu_packages}}"
    - name: Ensure Snap Packages
      snap: name="{{snap_packages}}"
    - name: Ensure Snap Packages Classic
      snap: classic=yes name="{{snap_classic_packages}}"
  handlers:
      - name: Restart Snapd
        systemd: name=snapd state=restarted
  roles:
    - role: make_install
      make_install_archive: "https://github.com/github/hub/releases/download/v{{hub_version}}/hub-linux-amd64-{{hub_version}}.tgz"
      make_install_exists: "/usr/local/bin/hub-{{hub_version}}.bin"
      make_install_command: |
        cd hub-linux-amd64-{{ hub_version }}
        ./install
        ln -s /usr/local/bin/hub /usr/local/bin/hub-{{ hub_version }}.bin
    - role: bazel
      when: bazel_version != ""
      tags: bazel
    - role: emacs
      when: emacs_version != ""
      tags: emacs
  tasks:
    - name: Git Config
      become: no
      git_config: name="{{item.key}}" value="{{item.value}}" scope=global
      with_dict: "{{ git_config | default({}) }}"
    - name: Ensure .vimrc
      become: no
      get_url:
        url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
        dest: ~/.vimrc
    - name: Spacemacs
      become: no
      shell: |
        set -euo pipefail
        [[ -d ~/.emacs.d ]] && rm -rf ~/.emacs.d
        [[ -f ~/.spacemacs ]] && rm ~/.spacemacs
        declare -a layers=(emacs-lisp rust csv better-defaults
                           clojure common-lisp git github markdown
                           javascript python ruby c-c++ shell-scripts
                           react ruby-on-rails yaml vagrant ansible
                           sql dash syntax-checking version-control)
        git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
        sed -E -e /dotspacemacs-editing-style/s/vim/emacs/ \
            -e "/^\\s+emacs-lisp\\s*\$/s/emacs-lisp/${layers[*]}/" \
            ~/.emacs.d/core/templates/.spacemacs.template > ~/.spacemacs
        emacs --batch --load ~/.emacs.d/init.el
        touch ~/.emacs.d/private/.done
      args:
        creates: $HOME/.emacs.d/private/.done
        executable: /bin/bash
    - name: Ensure Oh My Zsh
      become: no
      shell: |
        export SHELL=/bin/zsh
        sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: $HOME/.oh-my-zsh/oh-my-zsh.sh
  post_tasks:
    - name: Change The Default Shell to Zsh
      user: name="{{ansible_user}}" shell=/bin/zsh
      become: yes

