#!/usr/bin/env ansible-playbook
---
- name: Ubuntu
  hosts: localhost
  environment: "{{ local_env | default({}) }}"
  pre_tasks:
    - name: Change /etc/environment
      lineinfile:
          path: /etc/environment
          regexp: "^{{ item.key }}=.+"
          line: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ local_env | default({}) }}"
      notify: Restart Snapd
      become: yes
    - name: Ensure Useful Packages
      apt:
        update_cache: yes
        cache_valid_time: "{{ 3600*24*3 }}"
        name:
            - net-tools
            - zsh
            - git
            - openssh-server
            - vim
            - curl
            - fonts-noto
            - xsel
      become: yes
    - name: Ensure Snap Packages
      snap:
        name:
          - jq
      become: yes
  handlers:
      - name: Restart Snapd
        systemd: name=snapd state=restarted
        become: yes
  tasks:
    - name: Git Config
      git_config: name="{{item.key}}" value="{{item.value}}" scope=global
      with_dict: "{{ git_config | default({}) }}"
    - name: Ensure .vimrc
      get_url:
        url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
        dest: ~/.vimrc
    - name: Ensure Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: $HOME/.oh-my-zsh/oh-my-zsh.sh
