#!/usr/bin/env ansible-playbook
---
- name: Ubuntu
  hosts: localhost
  vars:
    hub_version: 2.11.1
  environment: "{{ local_env | default({}) }}"
  pre_tasks:
    - name: Change /etc/environment
      lineinfile:
          path: /etc/environment
          regexp: "^{{ item.key }}=.+"
          line: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ local_env | default({}) }}"
      notify: Restart Snapd
      become: yes
    - meta: flush_handlers
    - name: Ensure Useful Packages
      apt:
        update_cache: yes
        cache_valid_time: "{{ 3600*24*3 }}"
        name:
            - net-tools
            - zsh
            - git
            - openssh-server
            - vim
            - curl
            - fonts-noto
            - xsel
      become: yes
    - name: Ensure Libraries for Building Emacs 26
      apt:
        update_cache: yes
        cache_valid_time: "{{ 3600*24*3 }}"
        name:
            - libgtk-3-dev # for building emacs
            - libwebkitgtk-3.0-dev # for building emacs
            - libxpm-dev
            - libxpm-dev
            - libjpeg-dev
            - libgif-dev
            - libtiff5-dev
            - libgnutls28-dev
            - libtinfo-dev
            - libncurses5-dev
            - libvterm-dev
      become: yes
    - name: Ensure Snap Packages
      become: yes
      snap:
        name:
          - jq
    - name: Ensure Snap Packages Classic
      become: yes
      snap:
        classic: yes
        name:
          - google-cloud-sdk
    - name: Ensure Hub
      become: yes
      shell: |
        set -euo pipefail
        cd "$(mktemp -d)"
        wget https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tgz
        tar zxf hub-linux-amd64-{{ hub_version }}.tgz
        cd hub-linux-amd64-{{ hub_version }}
        ./install
        ln -s /usr/local/bin/hub /usr/local/bin/hub-{{ hub_version }}
      args:
        creates: /usr/local/bin/hub-{{ hub_version }}
  handlers:
      - name: Restart Snapd
        systemd: name=snapd state=restarted
        become: yes
  tasks:
    - name: Git Config
      git_config: name="{{item.key}}" value="{{item.value}}" scope=global
      with_dict: "{{ git_config | default({}) }}"
    - name: Ensure .vimrc
      get_url:
        url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
        dest: ~/.vimrc
    - name: Ensure Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: $HOME/.oh-my-zsh/oh-my-zsh.sh
