- name: Ensure Bazelisk
  get_url:
    url: "https://github.com/bazelbuild/bazelisk/releases/download/v{{bazelisk_version}}/bazelisk-linux-amd64"
    dest: /usr/bin/bazelisk
    mode: a+x

- name: Ensure a link to bazel
  file:
    path: /usr/bin/bazel
    src: /usr/bin/bazelisk
    state: link

- name: Using the bazel {{bazel_version}} as default
  copy:
    dest: /etc/profile.d/bazel.sh
    content: |
      USE_BAZEL_VERSION="{{bazel_version}}"
