- name: Ensure Bazel {{ bazel_version }}
  get_url: >
      url="https://github.com/bazelbuild/bazel/releases/download/{{bazel_version}}/bazel-{{bazel_version}}-linux-x86_64"
      dest="/usr/bin/bazel-real-{{bazel_version}}"
      mode=a+x
- name: Using the bazel {{bazel_version}} as default
  file: path=/usr/bin/bazel-real src="/usr/bin/bazel-real-{{bazel_version}}" state=link
