- name: Spacemacs
  shell: |
    set -euo pipefail
    [[ -d ~/.emacs.d ]] && rm -rf ~/.emacs.d
    [[ -f ~/.spacemacs ]] && rm ~/.spacemacs
    declare -a layers=(emacs-lisp rust csv better-defaults
                       clojure common-lisp git github markdown
                       javascript python ruby c-c++ shell-scripts
                       react ruby-on-rails yaml vagrant ansible
                       sql dash syntax-checking version-control)
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    sed -E -e /dotspacemacs-editing-style/s/vim/emacs/ \
        -e "/^\\s+emacs-lisp\\s*\$/s/emacs-lisp/${layers[*]}/" \
        ~/.emacs.d/core/templates/.spacemacs.template > ~/.spacemacs
    emacs --batch --load ~/.emacs.d/init.el
    touch ~/.emacs.d/private/.done
  args:
    creates: $HOME/.emacs.d/private/.done
    executable: /bin/bash
